UR5_C_MODEL_CONFIG = {
    'name': 'robot',
    'robot_description_param': "robot_description",
    'ik_solver': 'kdl',
    'base_link': "base_link",
    'end_link': "ee_link",
    'joint_states_topic': "/joint_states",
    'gripper_topic': '',
    'dof': 6,
    'q0': [0.30, -1.33, -1.80, -0.27, 1.50, 1.60],
    'joints': ['shoulder_pan_joint',
               'shoulder_lift_joint',
               'elbow_joint',
               'wrist_1_joint',
               'wrist_2_joint',
               'wrist_3_joint'],
    'namespace': 'costar',
    'robot_description_param': 'robot_description',
}
