#!/usr/bin/env python

'''
By Chris Paxton
(c) 2017 The Johns Hopkins University
See License for Details

This tool is designed to allow you to bring up task planning and reinforcement
learning experiments using the CTP library and Bullet3 physics. For
instructions see the readme.
'''
import pybullet as pb
pb.connect(pb.GUI)

from costar_task_plan.simulation import ParseBulletArgs
from main import main

if __name__ == '__main__':
    '''
    This simple tool should parse arguments and pass them to a simulation client.
    The client actually manages everything, including the ROS core.
    '''

    args = ParseBulletArgs()
    args['gui'] = False
    if args['profile']:
        import cProfile
        cProfile.run('main(args)')
    else:
        main(args)
