#!/usr/bin/env python

from costar_task_plan.simulation import ParseBulletArgs
from costar_task_plan.gym import BulletSimulationEnv
from costar_task_plan.agent import GetAgents, MakeAgent
from costar_task_plan.models import MakeModel

import time


def main(args):
    env = BulletSimulationEnv(**args)
    if 'agent' in args and args['agent'] is not None:
        agent = MakeAgent(env, args['agent'], **args)   
        agent.fit(num_iter=args['iter'])
    if 'model' in args and args['model'] is not None:
        model = MakeModel(taskdef=env.task, **args)
        model.train(**agent.data)

if __name__ == '__main__':
    '''
    This simple tool should parse arguments and pass them to a simulation client.
    The client actually manages everything, including the ROS core.
    '''

    args = ParseBulletArgs()
    print args
    if args['profile']:
        import cProfile
        cProfile.run('main(args)')
    else:
        main(args)
