#!/usr/bin/env python

from __future__ import print_function

import h5py
import matplotlib.pyplot as plt
from costar_models.datasets.image import GetJpeg, JpegToNumpy

def parse():
    import argparse
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument('filename', type=str, help="h5f file to load")
    return parser.parse_args()

filename = parse().filename
h5 = h5py.File(filename, "r")

print(h5.keys())
if "features" in h5.keys():
    img_key = "features"
else:
    img_key = "image"

data = h5[img_key]

for i in range(data.shape[0]):
    # Data is encoded as either a jpeg or a png
    # TODO: check what it was saved as.
    #print(i, data[i])
    plt.figure()
    plt.imshow(JpegToNumpy(data[i]))
    plt.show()