#!/usr/bin/env python

'''
Tools to collect a single data set for the robot learning task. We assume data
collection works via ros topic.
'''

import rospy

# Import everything from the "costar workshop assistant" definition for CTP
# robotics tasks
from costar_task_plan.robotics.workshop import *

def main(hz,**kwargs):
    '''
    Start up listeners for data collection, and run the main loop.
    '''
    rospy.init_node("ctp_data_collector")
    manager = ListenerManager(**kwargs)
    rate = rospy.Rate(hz)
    try:
        while not rospy.is_shutdown():
            rate.sleep()
    except rospy.RosInterruptException as e:
        pass

if __name__ == '__main__':
    #args = ParseWorkshopArgs()
    config = {
        "camera_depth_info_topic": "camera/depth_registered/info",
        "camera_rgb_info_topic": "camera/rgb/info",
        "camera_rgb_topic": "camera/rgb/image_raw",
        "camera_depth_topic": "camera/depth_registered/image_raw",
        "joints_topic": "joint_states",
        "world_frame": "base_link",
        }
    main(**config)


