#!/usr/bin/env python

'''
Use this script to launch the whole simulation, not the various launch files.
'''

import rospy

from costar_task_plan.gym import GazeboEnv
from costar_simulation import CostarSimulationManager, ParseGazeboArgs

if __name__ == '__main__':
    args = ParseGazeboArgs()

    try:
        if 'launch' in args and args['launch'] is not None:
            sim = CostarSimulationManager(**args)
            sim.run()
    except Exception as e:
        sim.shutdown()
        raise e

    rospy.init_node('simulation_manager_node')
    rate = rospy.Rate(10)
    while not rospy.is_shutdown():
        rate.sleep()

    sim.shutdown()
   
    

