#!/usr/bin/env python

'''
Use this script to launch the whole simulation, not the various launch files.
'''

import rospy

from costar_task_plan.gym import GazeboEnv
from costar_simulation import CostarSimulationManager, ParseGazeboArgs

if __name__ == '__main__':
    args = ParseGazeboArgs()
    if 'launch' in args and args['launch'] is not None:
        #env = GazeboEnv(args['launch'])
        sim = CostarSimulationManager(**args)
        sim.run()

    rospy.init_node('simulation_manager_node')
    rate = rospy.Rate(10)
    while not rospy.is_shutdown():
        rate.sleep()

    sim.shutdown()
   
    

